// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epggnqqnymxxkrvexpua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwZ2ducXFueW14eGtydmV4cHVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMjU2NDMsImV4cCI6MjA1OTYwMTY0M30.rAZoNsJkW7ouQxh0tXDfLl5K2d5OGaoRrVaOihHZ0YY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);